
FROM golang:1.24-alpine AS builder


WORKDIR /app


COPY core/go.mod core/go.sum ./

RUN go mod download

COPY core/ ./

RUN go build \
    -ldflags="-s -w" \
    -o /dockman-updater \
    ./cmd/updater/main.go

FROM scratch

WORKDIR /app

COPY --from=builder /dockman-updater .

EXPOSE 8869

CMD ["./dockman-updater"]
