set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

# generate files no moves
geno:
    just build
    docker run --rm -v "{{justfile_directory()}}:/workspace" gouda-proto:latest

# generate and copy out go files and remove go generated dir
gen:
    just geno
    just go
    just web

go:
    clear
    echo 'moving go files'
    rm -r ../backend/generated/*
    cp -r generated/go/* ../backend/generated/
    rm -r generated/go

web:
    clear
    echo 'moving web files'
    rm -r ../ui/src/gen/*
    cp -r generated/web/* ../frontend/src/gen/
    rm -r generated/web


# drop into a shell and interact with the image
# CTRL+D to exit
it:
    just build
    docker run --rm --name gouda_grpc_shell -v "{{justfile_directory()}}:/workspace" -it gouda-proto:latest /bin/bash

# build image
build:
	docker build . -t gouda-proto:latest

# build and push
bpsh:
	make build
	make push
